#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oliviaEvansC_Final
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TCC2023")]
	public partial class TCCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOffense(Offense instance);
    partial void UpdateOffense(Offense instance);
    partial void DeleteOffense(Offense instance);
    #endregion
		
		public TCCDataContext() : 
				base(global::oliviaEvansC_Final.Properties.Settings.Default.TCC2023ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TCCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TCCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TCCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TCCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<West> Wests
		{
			get
			{
				return this.GetTable<West>();
			}
		}
		
		public System.Data.Linq.Table<Southeast> Southeasts
		{
			get
			{
				return this.GetTable<Southeast>();
			}
		}
		
		public System.Data.Linq.Table<Offense> Offenses
		{
			get
			{
				return this.GetTable<Offense>();
			}
		}
		
		public System.Data.Linq.Table<Northeast> Northeasts
		{
			get
			{
				return this.GetTable<Northeast>();
			}
		}
		
		public System.Data.Linq.Table<Metro> Metros
		{
			get
			{
				return this.GetTable<Metro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.West")]
	public partial class West
	{
		
		private System.Nullable<int> _y2021;
		
		private System.Nullable<int> _y2022;
		
		private System.Nullable<int> _y2023;
		
		private int _id;
		
		public West()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2021", DbType="Int")]
		public System.Nullable<int> y2021
		{
			get
			{
				return this._y2021;
			}
			set
			{
				if ((this._y2021 != value))
				{
					this._y2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2022", DbType="Int")]
		public System.Nullable<int> y2022
		{
			get
			{
				return this._y2022;
			}
			set
			{
				if ((this._y2022 != value))
				{
					this._y2022 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2023", DbType="Int")]
		public System.Nullable<int> y2023
		{
			get
			{
				return this._y2023;
			}
			set
			{
				if ((this._y2023 != value))
				{
					this._y2023 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Southeast")]
	public partial class Southeast
	{
		
		private System.Nullable<int> _y2021;
		
		private System.Nullable<int> _y2022;
		
		private System.Nullable<int> _y2023;
		
		private int _id;
		
		public Southeast()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2021", DbType="Int")]
		public System.Nullable<int> y2021
		{
			get
			{
				return this._y2021;
			}
			set
			{
				if ((this._y2021 != value))
				{
					this._y2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2022", DbType="Int")]
		public System.Nullable<int> y2022
		{
			get
			{
				return this._y2022;
			}
			set
			{
				if ((this._y2022 != value))
				{
					this._y2022 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2023", DbType="Int")]
		public System.Nullable<int> y2023
		{
			get
			{
				return this._y2023;
			}
			set
			{
				if ((this._y2023 != value))
				{
					this._y2023 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Offenses")]
	public partial class Offense : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _OffenseType;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOffenseTypeChanging(string value);
    partial void OnOffenseTypeChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public Offense()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffenseType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string OffenseType
		{
			get
			{
				return this._OffenseType;
			}
			set
			{
				if ((this._OffenseType != value))
				{
					this.OnOffenseTypeChanging(value);
					this.SendPropertyChanging();
					this._OffenseType = value;
					this.SendPropertyChanged("OffenseType");
					this.OnOffenseTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Northeast")]
	public partial class Northeast
	{
		
		private System.Nullable<int> _y2021;
		
		private System.Nullable<int> _y2022;
		
		private System.Nullable<int> _y2023;
		
		private int _id;
		
		public Northeast()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2021", DbType="Int")]
		public System.Nullable<int> y2021
		{
			get
			{
				return this._y2021;
			}
			set
			{
				if ((this._y2021 != value))
				{
					this._y2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2022", DbType="Int")]
		public System.Nullable<int> y2022
		{
			get
			{
				return this._y2022;
			}
			set
			{
				if ((this._y2022 != value))
				{
					this._y2022 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2023", DbType="Int")]
		public System.Nullable<int> y2023
		{
			get
			{
				return this._y2023;
			}
			set
			{
				if ((this._y2023 != value))
				{
					this._y2023 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Metro")]
	public partial class Metro
	{
		
		private System.Nullable<int> _y2021;
		
		private System.Nullable<int> _y2022;
		
		private System.Nullable<int> _y2023;
		
		private int _id;
		
		public Metro()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2021", DbType="Int")]
		public System.Nullable<int> y2021
		{
			get
			{
				return this._y2021;
			}
			set
			{
				if ((this._y2021 != value))
				{
					this._y2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2022", DbType="Int")]
		public System.Nullable<int> y2022
		{
			get
			{
				return this._y2022;
			}
			set
			{
				if ((this._y2022 != value))
				{
					this._y2022 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y2023", DbType="Int")]
		public System.Nullable<int> y2023
		{
			get
			{
				return this._y2023;
			}
			set
			{
				if ((this._y2023 != value))
				{
					this._y2023 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
